# Generated by Django 5.1.6 on 2025-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_handling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="claims_created_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importsession",
            name="insured_created_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importsession",
            name="total_claimed_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="importsession",
            name="total_reimbursed_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
