# Generated by Django 5.1.6 on 2025-07-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_handling", "0002_importsession_claims_created_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importsession",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
