# Generated by Django 5.1.6 on 2025-07-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_handling", "0003_importsession_end_date_importsession_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="import_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="file_handling.importsession",
            ),
        ),
    ]
