# Generated by Django 5.1.6 on 2025-07-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_handling", "0004_file_import_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="import_session",
        ),
        migrations.AlterField(
            model_name="importsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("DONE", "Done"),
                    ("ERROR", "Error"),
                    ("DONE_WITH_ERRORS", "Done with Errors"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
