# Generated by Django 5.1.6 on 2025-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_handling", "0005_remove_file_import_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importsession",
            name="log_file_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
