# Generated by Django 5.1.6 on 2026-10-08 05:35

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_uploaded_by_role(apps, schema_editor):
    """Imports existants : rôle actuel de l'auteur (meilleure approximation disponible).
    Auteur supprimé -> rôle vide, traité comme un import d'admin territorial parti (file_handling/access.py)."""
    User = apps.get_model('users', 'CustomUser')
    role_of_author = Subquery(User.objects.filter(pk=OuterRef('user_id')).values('role')[:1])
    for model_name in ('File', 'ImportSession'):
        model = apps.get_model('file_handling', model_name)
        model.objects.filter(user__isnull=False, uploaded_by_role='').update(uploaded_by_role=role_of_author)


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0007_rename_file_name_file_name'),
        ('users', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_by_role',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='importsession',
            name='uploaded_by_role',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.RunPython(backfill_uploaded_by_role, migrations.RunPython.noop),
    ]
