# Generated by Django 5.1.6 on 2026-10-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0009_importsession_recap_files_sheet_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
