# Generated by Django 5.1.6 on 2026-10-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_handling', '0010_importsession_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importsession',
            name='progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='progress_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='importsession',
            name='step',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
