# Generated by Django 5.1.6 on 2025-07-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operators",
                to="countries.country",
            ),
            preserve_default=False,
        ),
    ]
