# Generated by Django 5.1.6 on 2025-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operator_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='modification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
