# Generated by Django 5.1.6 on 2026-10-09 16:20

import re
import unicodedata

import django.db.models.deletion
from django.db import migrations, models


def _text_key(value):
    """Copie figée de importer.reconciliation.normalize.text_key (une migration ne dépend pas du code vivant)."""
    text = re.sub(r'\s+', ' ', str(value or '').replace('’', "'").replace(' ', ' ')).strip()
    text = ''.join(c for c in unicodedata.normalize('NFKD', text) if not unicodedata.combining(c)).replace('�', '')
    return re.sub(r'\s+', ' ', text).strip().upper()


def fill_client_keys(apps, schema_editor):
    """Clé normalisée des employeurs existants ; deux employeurs d'un même pays qui ne diffèrent que par la casse,
    les accents ou les espaces bloqueraient la contrainte d'unicité : on s'arrête avec la liste à corriger."""
    Client = apps.get_model('core', 'Client')
    seen, clashes = {}, []
    for client in Client.objects.all():
        client.name_key = _text_key(client.name)
        client.save(update_fields=['name_key'])
        key = (client.country_id, client.name_key)
        if key in seen:
            clashes.append(f"{seen[key]} / {client.name} (pays {client.country_id})")
        seen.setdefault(key, client.name)
    if clashes:
        raise RuntimeError("Employeurs en double à fusionner avant la migration : " + ' ; '.join(clashes))


# Variantes d'écriture d'actes vues dans les fichiers réels (Donnees_SUNU, 09/10/2026) -> libellé retenu.
# Complétées ensuite par l'admin ; un acte sans alias garde son libellé.
ACT_ALIASES = {
    'Médicaments': ['Médicament', 'Médicaments'],
    'Médicaments non garantis': ['Médicament non garantis', 'Médicaments non garantis', 'Médicament non garanti',
                                 'Médicaments non garantie', 'Médicaments non garantiis', 'Médicament non garantie'],
    'Vitamines / Fortifiants': ['Vitamine', 'Vitamines', 'Vitamines / Fortifiants', 'Vitamines/Fortifiants',
                                'Vitamines ou Fortifiants', 'Vitamine / Fortifiant'],
    'Dépassement': ['Dépassement', 'Dépassements'],
    'Examens de laboratoire': ['Examen de laboratoire', 'Examens de laboratoire'],
    'Monture': ['Monture', 'Montures'],
    'Consultation généraliste': ['Consultation généraliste', 'Consultation Generaliste'],
    'Consultation spécialiste': ['Consultation spécialiste', 'Consultation Specialiste'],
}


def fill_act_aliases(apps, schema_editor):
    ActAlias = apps.get_model('core', 'ActAlias')
    for act_label, variants in ACT_ALIASES.items():
        for variant in variants:
            ActAlias.objects.update_or_create(alias_key=_text_key(variant),
                                              defaults={'alias_label': variant, 'act_label': act_label})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drop_old_claims_model'),
        ('countries', '0003_country_deactivation_requests'),
        ('file_handling', '0010_importsession_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('label_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_key', models.CharField(max_length=255, unique=True)),
                ('alias_label', models.CharField(max_length=255)),
                ('act_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'act aliases',
            },
        ),
        migrations.CreateModel(
            name='ActCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('label_key', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('S', 'Réglé'), ('C', 'Annulé')], default='S', max_length=1)),
                ('claim_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('claimed_amount', models.FloatField(default=0)),
                ('reimbursed_amount', models.FloatField(default=0)),
                ('lines_count', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('guarantee_label', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('S', 'Réglé'), ('C', 'Annulé')], default='S', max_length=1)),
                ('settlement_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reimbursed_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['claim_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='GuaranteePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('label_key', models.CharField(max_length=255)),
                ('coverage_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('coverage_rate_source', models.CharField(blank=True, choices=[('OBSERVED', "Observé à l'import"), ('MANUAL', "Saisi par l'admin territorial")], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(db_index=True, max_length=255)),
                ('other_names', models.JSONField(blank=True, default=list)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('consumption_limit', models.FloatField(blank=True, null=True)),
                ('is_deduced', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuredEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Assuré principal'), ('spouse', 'Conjoint(e)'), ('child', 'Enfant'), ('other', 'Autre')], default='primary', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=255)),
                ('number_key', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('main_responsible_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255)),
                ('reference_key', models.CharField(max_length=255)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=255)),
                ('number_key', models.CharField(db_index=True, max_length=255)),
                ('coverage_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('coverage_rate_source', models.CharField(blank=True, choices=[('OBSERVED', "Observé à l'import"), ('MANUAL', "Saisi par l'admin territorial")], default='', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COMPANY', 'Entreprise'), ('INDIVIDUAL', 'Particulier')], max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('name_key', models.CharField(db_index=True, max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='name_key',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.RunPython(fill_client_keys, migrations.RunPython.noop),
        migrations.RunPython(fill_act_aliases, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('country', 'name_key'), name='client_unique_per_country'),
        ),
        migrations.AddField(
            model_name='act',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='core.actcategory'),
        ),
        migrations.AddField(
            model_name='claim',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='countries.country'),
        ),
        migrations.AddField(
            model_name='claim',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.client'),
        ),
        migrations.AddField(
            model_name='claim',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_claims', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='core.act'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_lines', to='core.actcategory'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.claim'),
        ),
        migrations.AddField(
            model_name='guaranteeplan',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_plans', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='insured',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insureds', to='countries.country'),
        ),
        migrations.AddField(
            model_name='insured',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_insureds', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='claim',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.insured'),
        ),
        migrations.AddField(
            model_name='insuredemployer',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_insureds', to='core.client'),
        ),
        migrations.AddField(
            model_name='insuredemployer',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_insured_employers', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='insuredemployer',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_clients', to='core.insured'),
        ),
        migrations.AddField(
            model_name='insuredemployer',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.guaranteeplan'),
        ),
        migrations.AddField(
            model_name='insuredemployer',
            name='primary_insured_ref',
            field=models.ForeignKey(blank=True, help_text='Renseigner si l’assuré est conjoint ou enfant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents_in_clients', to='core.insured'),
        ),
        migrations.AddField(
            model_name='claim',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.insuredemployer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='countries.country'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_invoices', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_lines', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='operator',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='countries.country'),
        ),
        migrations.AddField(
            model_name='claimline',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_lines', to='core.operator'),
        ),
        migrations.AddField(
            model_name='claim',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.operator'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='countries.country'),
        ),
        migrations.AddField(
            model_name='partner',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_partners', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.partner'),
        ),
        migrations.AddField(
            model_name='claim',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.partner'),
        ),
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='countries.country'),
        ),
        migrations.AddField(
            model_name='payment',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_payments', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.partner'),
        ),
        migrations.AddField(
            model_name='claim',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='core.payment'),
        ),
        migrations.AddField(
            model_name='policy',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='countries.country'),
        ),
        migrations.AddField(
            model_name='policy',
            name='employers',
            field=models.ManyToManyField(blank=True, related_name='policies', to='core.client'),
        ),
        migrations.AddField(
            model_name='policy',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_policies', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='insuredemployer',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_employers', to='core.policy'),
        ),
        migrations.AddField(
            model_name='guaranteeplan',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.policy'),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.policy'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='countries.country'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_subscribers', to='file_handling.importsession'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='insured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='core.insured'),
        ),
        migrations.AddField(
            model_name='policy',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='core.subscriber'),
        ),
        migrations.AddConstraint(
            model_name='insured',
            constraint=models.UniqueConstraint(condition=models.Q(('card_number__isnull', False)), fields=('country', 'card_number'), name='insured_card_unique_per_country'),
        ),
        migrations.AddConstraint(
            model_name='operator',
            constraint=models.UniqueConstraint(fields=('country', 'name_key'), name='operator_unique_per_country'),
        ),
        migrations.AddConstraint(
            model_name='claimline',
            constraint=models.UniqueConstraint(fields=('claim', 'line_number'), name='claim_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('country', 'name_key'), name='partner_unique_per_country'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('country', 'partner', 'number_key'), name='invoice_unique_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('country', 'partner', 'reference_key'), name='payment_unique_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='insuredemployer',
            constraint=models.UniqueConstraint(fields=('insured', 'policy', 'employer'), name='membership_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='guaranteeplan',
            constraint=models.UniqueConstraint(fields=('policy', 'label_key'), name='plan_unique_per_policy'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['country', 'settlement_date'], name='claim_country_settled_idx'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('country', 'number'), name='claim_unique_per_country'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('country', 'kind', 'name_key'), name='subscriber_unique_per_country'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('country', 'number_key'), name='policy_unique_per_country'),
        ),
    ]
