# Generated by Django 5.1.6 on 2026-10-09 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_new_claims_model'),
        ('countries', '0003_country_deactivation_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principals', models.JSONField(blank=True, default=list)),
                ('action', models.CharField(choices=[('ATTACH', 'Rattachement à un autre principal'), ('ROLE', 'Changement de rôle'), ('MERGE', 'Fusion de deux fiches'), ('RENAME', 'Nom retenu')], max_length=10)),
                ('summary', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_changes', to='countries.country')),
                ('insured', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_changes', to='core.insured')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_changes', to='core.policy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
