# Generated by Django 5.1.6 on 2026-10-09 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_family_change'),
        ('countries', '0003_country_deactivation_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_changes', to='countries.country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='refchange_object_idx')],
            },
        ),
    ]
