# Generated by Django 5.1.6 on 2026-10-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reference_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteeplan',
            name='observed_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='observed_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
