# Generated by Django 5.1.6 on 2026-10-10 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_observed_rate'),
        ('countries', '0003_country_deactivation_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source', models.CharField(choices=[('MANUAL', 'Saisie'), ('IMPORT', 'Import de fichier')], default='MANUAL', max_length=10)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='core.client')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='countries.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiums_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client_id', 'start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='premium_period_valid'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='premium_amount_positive'), models.UniqueConstraint(fields=('client', 'start_date'), name='premium_unique_start')],
            },
        ),
    ]
