# Generated by Django 5.1.6 on 2026-10-10 05:24
# Suppression de l'ancienne prime unique de l'employeur (sans période) et de son historique : les primes sont
# désormais dans Premium (0009), par période couverte. Validé par l'utilisateur le 10/10/2026.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='prime',
        ),
        migrations.DeleteModel(
            name='ClientPrimeHistory',
        ),
    ]
