# Generated by Django 5.1.6 on 2025-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=4, unique=True)),
                (
                    "currency_code",
                    models.CharField(
                        blank=True, default="XOF", max_length=10, null=True
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(
                        blank=True, default="F CFA", max_length=50, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
