# Generated by Django 5.1.6 on 2026-10-06 23:49

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='country_name_unique_ci', violation_error_message='Un pays avec ce nom existe déjà.'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('code')), name='country_code_unique_ci', violation_error_message='Un pays avec ce code existe déjà.'),
        ),
    ]
